## Hypothesis Testing Exercise :

## 4) TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences


In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import chi2_contingency

In [2]:
customer_data = pd.read_csv('Costomer+OrderForm.csv')

In [3]:
customer_data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [5]:
customer_data.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [6]:
customer_data.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [7]:
customer_data.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [8]:
customer_data.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [9]:
# Make a contingency table
table = np.array([[271,267,269,280],[29,33,31,20]])
table

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [10]:
# Chi2 contengency independence test
chi2,p_val,dof,expected = chi2_contingency(table)

In [11]:
print('Chi-squared value : ',round(chi2,5))
print('P-val             : ',round(p_val,5))
print('Degree of Freedom : ',dof)
print('Expected Table    :\n',expected)

Chi-squared value :  3.85896
P-val             :  0.2771
Degree of Freedom :  3
Expected Table    :
 [[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


## P_Value = 0.27 (27%).

## HYPOTHESIS FORMULATION:

## H0: The defective % doesnot varies by centre.

## Ha: The defective % varies by centre.

## Level of significance : 5%. (0.05)

## Since the p_value is 0.27 (27%) > than the level of significance 0.05(5%) (p_value > LOS)

## so, we do not reject the Null Hypothesis (H0).

## Observation - The defective % doesnot varies by centre.